export const FOODS_LOADING = 'FOODS_LOADING';
export const ADD_FOODS = 'ADD_FOODS';
export const FOODS_FAILED = 'FOODS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORTIE';