export const FOODS_LOADING = 'FOODS_LOADING';
export const ADD_FOODS = 'ADD_FOODS';
export const FOODS_FAILED = 'FOODS_FAILED';

export const FLAVORS_LOADING = 'FLAVORS_LOADING';
export const ADD_FLAVORS = 'ADD_FLAVORS';
export const FLAVORS_FAILED = 'FLAVORS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORTIE';


export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED';
export const SELECT_LOCATION = 'SELECT_LOCATION';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const DROP_CART = 'DROP_CART'